# Generated by Django 5.1.6 on 2025-02-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('author', 'author of the book'), ('buyer', 'buyer of the book'), ('reader', 'reader of the book')], default='reader', max_length=10),
        ),
    ]
