# Generated by Django 5.1.5 on 2025-01-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('publication_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('is_available', models.BooleanField()),
            ],
        ),
    ]
