# Generated by Django 5.1.6 on 2025-02-15 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
